# Generated by Django 4.2.7 on 2023-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FemaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SL', models.IntegerField()),
                ('Starting_Time', models.DateTimeField()),
                ('Starting_Point', models.CharField(max_length=255)),
                ('Route', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MaleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SL', models.IntegerField()),
                ('Starting_Time', models.DateTimeField()),
                ('Starting_Point', models.CharField(max_length=255)),
                ('Route', models.TextField()),
            ],
        ),
    ]
