# Generated by Django 4.2.7 on 2023-12-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_shedual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='malemodel',
            old_name='Route',
            new_name='Root',
        ),
        migrations.RenameField(
            model_name='malemodel',
            old_name='SL',
            new_name='SLL',
        ),
        migrations.RenameField(
            model_name='malemodel',
            old_name='Starting_Point',
            new_name='Start_Point',
        ),
        migrations.RenameField(
            model_name='malemodel',
            old_name='Starting_Time',
            new_name='Start_Time',
        ),
    ]
