# Generated by Django 4.2.7 on 2023-12-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
